evChurch/apps/grupos/urls.py
from django.urls import path, include
from . import views

app_name='grupos'

urlpatterns = [
    path("grupos/", views.GruposView.as_view(), name="grupos_index"),
    path("grupos/detalhes/<int:pk>/",
        views.GruposDetailView.as_view(), name="grupos_show"),
    path("grupos/cadastrar/",views.grupos_create, name="grupos_create"),
    path("grupos/<int:pk>/editar/",views.grupos_edit, name="grupos_edit"),
    path("grupos/<int:pk>/excluir/", views.grupos_delete, name="grupos_delete")
]

evChurch/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .apps.core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(home), name="root_path"),
    path('core/', include('evChurch.apps.core.urls', namespace='core')),
    path('auth/',
        include('evChurch.apps.authorization.urls', namespace='authorization')),
    path('usuarios/',
        include('evChurch.apps.usuarios.urls', namespace='usuarios')),
    path('instituicoes/',
        include('evChurch.apps.instituicoes.urls', namespace='instituicoes')),
    path('grupos/',
        include('evChurch.apps.grupos.urls', namespace='grupos')),
    path('agenda/',
         include('evChurch.apps.agenda.urls', namespace='agenda')),
    path('ambientes/',
         include('evChurch.apps.ambientes.urls', namespace='ambientes')),
    path('evento/',
         include('evChurch.apps.evento.urls', namespace='evento'))
]

evChurch/apps/grupos/models.py
from django.db import models
from  ..instituicoes.models import Instituicao

class Tipo(models.Model):
    """Modelo responsável por reunir informações sobre os tipos de grupos"""
    descricao = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.descricao

class Perfil(models.Model):
    """Modelo responsável por reunir informações sobre os perfis dos grupos"""
    descricao = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.descricao

class Grupos(models.Model):
    """Modelo responsavel por reunir informações sobre os grupos de uma instituição"""
    nome = models.CharField(max_length=100, null=True, blank=True)
    tipo = models.ForeignKey(Tipo, null=True, blank=True, on_delete=models.CASCADE)
    data_abertura = models.DateField(auto_now_add=True, null=True, blank=True)
    perfil = models.ForeignKey(Perfil, null=True, blank=True, on_delete=models.CASCADE)
    lider = models.CharField(max_length=100, null=True, blank=True)
    logradouro = models.CharField(max_length=120, null=True, blank=True)
    numero = models.CharField(max_length=10, null=True, blank=True)
    bairro = models.CharField(max_length=100, null=True, blank=True)
    complemento = models.CharField(max_length=80, blank=True, null=True)
    cep = models.CharField(max_length=9, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    telefone = models.CharField(max_length=12, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    dia_semana = models.CharField(max_length=50, null=True, blank=True)
    turno =  models.CharField(max_length=20, null=True, blank=True)
    instituicao = models.ForeignKey(Instituicao, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

evChurch/apps/grupos/forms.py
from django import forms
from localflavor.br.forms import BRStateChoiceField
from ..usuarios.models import Usuario
from .models import *

TURNO_CHOICES = [
    ('-----', '-----'),
    ('Matutino', 'Matutino'),
    ('Vespertino', 'Vespertino'),
    ('Noturno', 'Noturno'),
]

DIA_SEMANA_CHOICES = [
    ('-----', '-----'),
    ('Domingo', 'Domingo'),
    ('Segunda-Feira', 'Segunda-Feira'),
    ('Terça-Feira', 'Terça-Feira'),
    ('Quarta-Feira', 'Quarta-Feira'),
    ('Quinta-Feira', 'Quinta-Feira'),
    ('Sexta-Feira', 'Sexta-Feira'),
    ('Sábado', 'Sábado'),
]

class SearchGrupos(forms.Form):
    """Formulário para consulta de grupos da view que lista grupos
    de forma genérica"""

    nome = forms.CharField(max_length=90, required=False)
    lider = forms.CharField(required=False)
    dia_semana = forms.CharField(required=False)
    perfil = forms.ModelChoiceField(queryset=Perfil.objects.all(), required=False, label="Perfil")

class GruposCreateForm(forms.ModelForm):
    """Formulário para criação de grupos"""
    nome = forms.CharField(required=True, label="Nome")
    tipo = forms.ModelChoiceField(queryset=Tipo.objects.all(), required=True, label="Tipo")
    perfil = forms.ModelChoiceField(queryset=Perfil.objects.all(), required=True, label="Perfil")
    lider = forms.CharField(required=True, label="Líder")
    data_abertura = forms.CharField(widget=forms.TextInput(attrs={'type':'date'}), required=False, label="Data de Abertura")
    turno = forms.ChoiceField(choices=TURNO_CHOICES, required=True)
    dia_semana = forms.ChoiceField(choices=DIA_SEMANA_CHOICES, required=True)
    instituicao = forms.ModelChoiceField(queryset=Instituicao.objects.all(), required=True, label="Instituição")
    cep = forms.CharField(required=True)
    logradouro = forms.CharField(required=True)
    numero = forms.CharField(required=True)
    cidade = forms.CharField(required=True)
    bairro = forms.CharField(required=True)
    uf = forms.CharField(required=True, label="UF")

    class Meta:
        model = Grupos
        fields = ('__all__')

evChurch/apps/grupos/views.py
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from ..core.generic_views import SearchCustomView, CustomDetailView
from .forms import *
from django.http import HttpResponse

@method_decorator(login_required, name='dispatch')
class GruposView(SearchCustomView):
    """
    View para consulta de grupos
    """
    form_class = SearchGrupos
    model = Grupos
    order_field = "nome"
    template_name = "grupos/index.html"
    page_title = "Grupos"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("grupos:grupos_index"), "Grupos")
    ]

    def get_queryset(self):
        """
        Altera o filtro do grupo ::
        """
        queryset = super(GruposView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class GruposDetailView(CustomDetailView):
    """
    View para exibição dos detalhes dos grupos
    """
    model = Grupos
    template_name = "grupos/detail.html"
    page_title = "Grupos"

    def get_context_data(self, **kwargs):
        context = super(GruposDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("grupos:grupos_index"), "Grupos"),
            ("#", self.get_object().id)
        ]

        return context

@login_required
@permission_required("grupos.add_grupo", raise_exception=True)
def grupos_create(request):
    """View para Criar um grupos"""
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("grupos:grupos_index"), "Grupos"),
        (reverse("grupos:grupos_create"), "Novo Grupo")
    ]

    form = GruposCreateForm()
    if request.method == 'POST':
        form = GruposCreateForm(request.POST)

        if form.is_valid():
            grupo = form.save(commit=False)
            grupo.save()

            messages.success(request, "Grupo cadastrado com sucesso")
            return redirect(reverse("grupos:grupos_show", args=[grupo.pk]))

    return render(request, "grupos/cadastro.html", locals())

@login_required
@permission_required("grupos.add_grupo", raise_exception=True)
def grupos_edit(request, pk):
    """"View para Editar os Grupos"""
    grupo = get_object_or_404(Grupos, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("grupos:grupos_index"), "Grupos"),
        (reverse("grupos:grupos_show", args=[pk]), grupo.id),
        ("#", "Editar")
    ]

    form = GruposCreateForm(instance=grupo)

    if request.method == 'POST':
        form = GruposCreateForm(request.POST, request.FILES, instance=grupo)

        if form.is_valid():
            grupo = form.save(commit=False)
            grupo.save()

            messages.success(request, "Grupos alterado com sucesso.")
            return redirect(reverse("grupos:grupos_show", args=[grupo.pk]))

    return render(request, "grupos/editar.html", locals())

@login_required
@permission_required("grupos.add_grupo", raise_exception=True)
def grupos_delete(request, pk):
    """
    View responsável por deletar um grupos
    """
    grupo = get_object_or_404(Grupos, pk=pk)

    grupo.delete()
    messages.success(request, "Grupo deletado com sucesso!")
    return HttpResponse("Grupo deletado com sucesso!")

evChurch/apps/grupos/templates/grupos/cadastro.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/grupo.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Cadastrar Grupo</h1>
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
        {% include "grupos/form.html" %}
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'grupos:grupos_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/usuario.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/grupos/templates/grupos/detail.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/grupo.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h1 class="title">{{ page_title }}: {{ grupo.id }}</h1>
        </div>
        <table class="table table-bordered table-striped">
          <tr>
            <td><strong>Nome:</strong><br> {{ grupos.nome|default:"Não informado" }}</td>
            <td><strong>Tipo:</strong><br> {{ grupos.tipo|default:"Não informado" }}</td>
            <td><strong>Líder:</strong><br> {{ grupos.lider|default:"Não informado" }}</td>
            <td><strong>Perfil:</strong><br> {{ grupos.perfil|default:"Não informado" }}</td>
            <td><strong>Data Abertura:</strong><br> {{ grupos.data_abertura|default:"Não informado" }}</td>
          </tr>
          <tr>
             <td><strong>Logradouro:</strong><br> {{ grupos.logradouro|default:"Não informado" }}</td>
             <td><strong>Número:</strong><br> {{ grupos.numero|default:"Não informado" }}</td>
             <td><strong>Bairro:</strong><br> {{ grupos.bairro|default:"Não informado" }}</td>
             <td><strong>Cidade:</strong><br> {{ grupos.cidade|default:"Não informado" }}</td>
             <td><strong>UF:</strong><br> {{ grupos.uf|default:"Não informado" }}</td>
          </tr>
            <tr>
             <td><strong>Dia do Encontro:</strong><br> {{ grupos.dia_semana|default:"Não informado" }}</td>
             <td colspan="4"><strong>Turno:</strong><br> {{ grupos.turno|default:"Não informado" }}</td>
          </tr>
        </table>
      </div>
    </div>
      <div class="form-row">
        <div class="form -btn-actions col">
          <a href="{% url 'grupos:grupos_index' %}" class="btn btn-default"><< Voltar</a>
        </div>
      </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/grupos/templates/grupos/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/grupo.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Editar Grupo</h1>
      <ol class="breadcrumb">
        <li class="active">Preencha os campos corretamente</li>
      </ol>
      <form class="form" method="POST">
        {% csrf_token %}
        {% include "grupos/form_edit.html" %}
        <!-- {% bootstrap_form form %} -->
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'grupos:grupos_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/grupos/templates/grupos/form.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.tipo required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.lider required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.data_abertura required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.perfil required_css_class="required" %}
  </div>
    <div class="col-3">
    {% bootstrap_field form.dia_semana required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.turno required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-3">
    {% bootstrap_field form.cep required_css_class="required" %}
  </div>
    <div class="col-5">
    {% bootstrap_field form.logradouro required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.numero required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.complemento required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-5">
    {% bootstrap_field form.cidade required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.bairro required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.uf required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/grupo.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/grupos/templates/grupos/form_edit.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.tipo required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.lider required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.data_abertura required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.perfil required_css_class="required" %}
  </div>
    <div class="col-3">
    {% bootstrap_field form.dia_semana required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.turno required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-3">
    {% bootstrap_field form.cep required_css_class="required" %}
  </div>
    <div class="col-5">
    {% bootstrap_field form.logradouro required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.numero required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.complemento required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-5">
    {% bootstrap_field form.cidade required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.bairro required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.uf required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/grupo.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/grupos/templates/grupos/index.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/grupo.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>

      </div>
    </div>
  </div>
  <div class="row-list">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered table-striped">
        <thead>
          <th>Ações</th>
          <th>Nome</th>
          <th>Perfil </th>
          <th>Líder </th>
          <th>Dia</th>
        </thead>
        <tbody>
          {% for grupo in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'grupos:grupos_show' grupo.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'grupos:grupos_edit' grupo.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:grupoDelete({{grupo.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ grupo.nome|default:"Não informado"}}</td>
              <td>{{ grupo.perfil|default:"Não informado"}}</td>
              <td>{{ grupo.lider|default:"Não informado"}}</td>
              <td>{{ grupo.dia_semana|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de um grupo -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente esse grupo?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirGrupo" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function grupoDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirGrupo" ).click(function() {
        $.ajax({
          url: pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}