evChurch/apps/agenda/urls.py
from django.urls import path, include
from . import views

app_name='agenda'

urlpatterns = [
    path("agenda/", views.AgendaView.as_view(), name="agenda_index"),
    path("agenda/detalhes/<int:pk>/",
        views.AgendaDetailView.as_view(), name="agenda_show"),
    path("agenda/cadastrar/",views.agenda_create, name="agenda_create"),
    path("agenda/<int:pk>/editar/",views.agenda_edit, name="agenda_edit"),
    path("agenda/<int:pk>/excluir/", views.agenda_delete, name="agenda_delete")
]

evChurch/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .apps.core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(home), name="root_path"),
    path('core/', include('evChurch.apps.core.urls', namespace='core')),
    path('auth/',
        include('evChurch.apps.authorization.urls', namespace='authorization')),
    path('usuarios/',
        include('evChurch.apps.usuarios.urls', namespace='usuarios')),
    path('instituicoes/',
        include('evChurch.apps.instituicoes.urls', namespace='instituicoes')),
    path('grupos/',
        include('evChurch.apps.grupos.urls', namespace='grupos')),
    path('agenda/',
         include('evChurch.apps.agenda.urls', namespace='agenda')),
    path('ambientes/',
         include('evChurch.apps.ambientes.urls', namespace='ambientes')),
    path('evento/',
         include('evChurch.apps.evento.urls', namespace='evento'))
]

evChurch/apps/agenda/models.py
from django.db import models
from ..instituicoes.models import Instituicao
from ..usuarios.models import Usuario

class TipoReuniao(models.Model):
    """Modelo responsável por reunir informações sobre os tipos de reuniões da instituição"""
    descricao = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.descricao

class Agenda(models.Model):
    """Modelo responsável por reunir informações sobre a agenda da instituição"""
    instituicao = models.ForeignKey(Instituicao, null=True, blank=True, on_delete=models.CASCADE)
    reuniao = models.ForeignKey(TipoReuniao, null=True, blank=True, on_delete=models.CASCADE)
    data_inicial = models.DateField()
    data_final = models.DateField()
    horario_entrada = models.CharField(max_length=5, null=True, blank=True)
    horario_saida = models.CharField(max_length=5, null=True, blank=True)
    responsavel = models.CharField(max_length=100, null=True, blank=True)
    aberto_publico = models.CharField(max_length=3, null=True, blank=True)
    telefone = models.CharField(max_length=12, null=True, blank=True)
    titulo = models.CharField(max_length=100, null=True, blank=True)
    descricao = models.CharField(max_length=500, null=True, blank=True)
    local = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.titulo

class DiaSemana(models.Model):
    """Modelo responsavel por agrupar os dias da semana"""
    descricao = models.CharField(max_length=200, null=True, blank=True)
    agenda = models.ForeignKey(Agenda, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao

evChurch/apps/agenda/forms.py
from django import forms
from localflavor.br.forms import BRStateChoiceField
from ..instituicoes.models import Instituicao
from .models import *

ESCOLHA_CHOICES = [
    ('-----', '-----'),
    ('Sim', 'Sim'),
    ('Não', 'Não')
]

class SearchAgenda(forms.Form):
    """Formulário para consulta de agendas da view que lista agendas
    de forma genérica"""

    tipo_reuniao = forms.ModelChoiceField(queryset=TipoReuniao.objects.all(), required=False, label="Reunião")
    responsavel = forms.CharField(required=False)
    instituicao = forms.ModelChoiceField(queryset=Instituicao.objects.all(), required=False, label="Instituição")

class AgendaCreateForm(forms.ModelForm):
    """Formulário para criação de uma agenda"""
    reuniao = forms.ModelChoiceField(queryset=TipoReuniao.objects.all(), required=True, label="Reunião")
    responsavel = forms.CharField(required=True)
    instituicao = forms.ModelChoiceField(queryset=Instituicao.objects.all(), required=True, label="Instituição")
    data_inicial = forms.CharField(widget=forms.TextInput(attrs={'type':'date'}), required=False, label="Data Inicial")
    data_final = forms.CharField(widget=forms.TextInput(attrs={'type':'date'}), required=False, label="Data Final")
    horario_entrada = forms.CharField(required=True)
    horario_saida = forms.CharField(required=True)
    aberto_publico = forms.ChoiceField(choices=ESCOLHA_CHOICES, required=True, label="Aberto ao Público")

    class Meta:
        model = Agenda
        fields = ('__all__')

evChurch/apps/agenda/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from ..core.generic_views import SearchCustomView, CustomDetailView
from django.http import HttpResponse
from .forms import *
from .models import Agenda

@method_decorator(login_required, name='dispatch')
class AgendaView(SearchCustomView):
    """
    View para consulta de agendas
    """
    form_class = SearchAgenda
    model = Agenda
    order_field = "titulo"
    template_name = "agenda/index.html"
    page_title = "Agenda"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("agenda:agenda_index"), "Agenda")
    ]

    def get_queryset(self):
        """
        Altera o filtro da agenda ::
        """
        queryset = super(AgendaView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class AgendaDetailView(CustomDetailView):
    """
    View para exibição dos detalhes das agendas
    """
    model = Agenda
    template_name = "agenda/detail.html"
    page_title = "Agenda"

    def get_context_data(self, **kwargs):
        context = super(AgendaDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("agenda:agenda_index"), "Agenda"),
            ("#", self.get_object().id)
        ]

        return context

@login_required
@permission_required("agenda.add_agenda", raise_exception=True)
def agenda_create(request):
    """View para Criar uma agenda"""
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("agenda:agenda_index"), "Agenda"),
        (reverse("agenda:agenda_create"), "Nova Agenda")
    ]

    form = AgendaCreateForm()

    if request.method == 'POST':
        form = AgendaCreateForm(request.POST)
        if form.is_valid():
            agenda = form.save(commit=False)
            agenda.save()

            messages.success(request, "Agenda cadastrada com sucesso")
            return redirect(reverse("agenda:agenda_show", args=[agenda.pk]))

    return render(request, "agenda/cadastro.html", locals())

@login_required
@permission_required("agenda.add_agenda", raise_exception=True)
def agenda_edit(request, pk):
    """"View para Editar as Agendas"""
    agenda = get_object_or_404(Agenda, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("agenda:agenda_index"), "Agenda"),
        (reverse("agenda:agenda_show", args=[pk]), agenda.id),
        ("#", "Editar")
    ]

    form = AgendaCreateForm(instance=agenda)

    if request.method == 'POST':
        form = AgendaCreateForm(request.POST, request.FILES, instance=agenda)

        if form.is_valid():
            agenda = form.save(commit=False)
            agenda.save()

            messages.success(request, "Agenda alterado com sucesso.")
            return redirect(reverse("agenda:agenda_show", args=[agenda.pk]))

    return render(request, "agenda/editar.html", locals())

@login_required
@permission_required("agenda.add_agenda", raise_exception=True)
def agenda_delete(request, pk):
    """
    View responsável por deletar uma agenda
    """
    agenda = get_object_or_404(Agenda, pk=pk)

    agenda.delete()
    messages.success(request, "Agenda deletada com sucesso!")
    return HttpResponse("Agenda deletada com sucesso!")

evChurch/apps/agenda/templates/agenda/cadastro.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/agenda.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Cadastrar Agenda</h1>
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
        {% include "agenda/form.html" %}
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'agenda:agenda_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/agenda/templates/agenda/detail.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/agenda.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h1 class="title">{{ page_title }}: {{ agenda.id }}</h1>
        </div>
        <table class="table table-bordered table-striped">
          <tr>
            <td><strong>Título:</strong><br> {{ agenda.titulo|default:"Não informado" }}</td>
            <td><strong>Local:</strong><br> {{ agenda.local|default:"Não informado" }}</td>
            <td><strong>Instituição:</strong><br> {{ agenda.instituicao|default:"Não informado" }}</td>
            <td><strong>Responsável:</strong><br> {{ agenda.responsavel|default:"Não informado" }}</td>
            <td><strong>Descrição:</strong><br> {{ agenda.descricao|default:"Não informado" }}</td>
          </tr>
            <tr>
             <td colspan="2"><strong>Data e Horário:</strong><br>
                 De {{ agenda.data_inicial|date:"d/m/Y" }} às {{ agenda.horario_entrada|default:"Não informado" }} até
                 {{ agenda.data_final|date:"d/m/Y" }} às {{ agenda.horario_saida|default:"Não informado" }}
             </td>
                <td><strong>Tipo:</strong><br> {{ agenda.reuniao|default:"Não informado" }}</td>
                <td><strong>Aberto:</strong><br> {{ agenda.aberto_publico|default:"Não informado" }}</td>
                <td><strong>Contato:</strong><br> {{ agenda.telefone|default:"Não informado" }}</td>
          </tr>
        </table>
      </div>
    </div>
      <div class="form-row">
        <div class="form -btn-actions col">
          <a href="{% url 'agenda:agenda_index' %}" class="btn btn-default"><< Voltar</a>
        </div>
      </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/agenda/templates/agenda/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/agenda.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Editar Agenda</h1>
      <ol class="breadcrumb">
        <li class="active">Preencha os campos corretamente</li>
      </ol>
      <form class="form" method="POST">
        {% csrf_token %}
        {% include "agenda/form_edit.html" %}
        <!-- {% bootstrap_form form %} -->
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'agenda:agenda_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/agenda/templates/agenda/form.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.titulo required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.local required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.responsavel required_css_class="required" %}
  </div>
  <div class="col-8">
    {% bootstrap_field form.descricao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.data_inicial required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.horario_entrada required_css_class="required" %}
  </div>
    <div class="col-3">
    {% bootstrap_field form.data_final required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.horario_saida required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-4">
    {% bootstrap_field form.aberto_publico required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.reuniao required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/agenda/templates/agenda/form_edit.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.titulo required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.local required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.responsavel required_css_class="required" %}
  </div>
  <div class="col-8">
    {% bootstrap_field form.descricao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.data_inicial required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.horario_entrada required_css_class="required" %}
  </div>
    <div class="col-3">
    {% bootstrap_field form.data_final required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.horario_saida required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-4">
    {% bootstrap_field form.aberto_publico required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.reuniao required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/agenda/templates/agenda/index.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/agenda.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>

      </div>
    </div>
  </div>
  <div class="row-list">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered table-striped">
        <thead>
          <th>Ações</th>
          <th>Responsável</th>
          <th>Instituição </th>
          <th>Aberto </th>
          <th>Título</th>
          <th>Dia</th>
        </thead>
        <tbody>
          {% for agenda in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'agenda:agenda_show' agenda.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'agenda:agenda_edit' agenda.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:agendaDelete({{agenda.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ agenda.responsavel|default:"Não informado"}}</td>
              <td>{{ agenda.instituicao|default:"Não informado"}}</td>
              <td>{{ agenda.aberto_publico|default:"Não informado"}}</td>
              <td>{{ agenda.titulo|default:"Não informado"}}</td>
              <td>{{ agenda.data_inicial|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de uma agenda -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente essa agenda?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirAgenda" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function agendaDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirAgenda" ).click(function() {
        $.ajax({
          url: pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}