evChurch/apps/evento/urls.py
from django.urls import path, include
from . import views

app_name='evento'

urlpatterns = [
    path("evento/", views.EventoView.as_view(), name="evento_index"),
    path("evento/detalhes/<int:pk>/",
        views.EventoDetailView.as_view(), name="evento_show"),
    path("evento/cadastrar/",views.evento_create, name="evento_create"),
    path("evento/<int:pk>/editar/",views.evento_edit, name="evento_edit"),
    path("evento/<int:pk>/excluir/", views.evento_delete, name="evento_delete")
]

evChurch/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .apps.core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(home), name="root_path"),
    path('core/', include('evChurch.apps.core.urls', namespace='core')),
    path('auth/',
        include('evChurch.apps.authorization.urls', namespace='authorization')),
    path('usuarios/',
        include('evChurch.apps.usuarios.urls', namespace='usuarios')),
    path('instituicoes/',
        include('evChurch.apps.instituicoes.urls', namespace='instituicoes')),
    path('grupos/',
        include('evChurch.apps.grupos.urls', namespace='grupos')),
    path('agenda/',
         include('evChurch.apps.agenda.urls', namespace='agenda')),
    path('ambientes/',
         include('evChurch.apps.ambientes.urls', namespace='ambientes')),
    path('evento/',
         include('evChurch.apps.evento.urls', namespace='evento'))
]

evChurch/apps/evento/models.py
from django.db import models
from ..instituicoes.models import Instituicao

class Evento(models.Model):
    """Modelo responsável por reunir informações sobre a agenda da instituição"""
    instituicao = models.ForeignKey(Instituicao, null=True, blank=True, on_delete=models.CASCADE)
    data_inicial = models.DateField()
    data_final = models.DateField()
    horario_entrada = models.CharField(max_length=5, null=True, blank=True)
    horario_saida = models.CharField(max_length=5, null=True, blank=True)
    responsavel = models.CharField(max_length=100, null=True, blank=True)
    aberto_publico = models.CharField(max_length=3, null=True, blank=True)
    telefone = models.CharField(max_length=12, null=True, blank=True)
    nome = models.CharField(max_length=100, null=True, blank=True)
    local = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        permissions = (
            ('pode_cadastrar_evento', 'Pode cadastrar evento'),
        )

    def __str__(self):
        return self.nome

evChurch/apps/evento/forms.py
from django import forms
from .models import *
from ..instituicoes.models import Instituicao

ESCOLHA_CHOICES = [
    ('-----', '-----'),
    ('Sim', 'Sim'),
    ('Não', 'Não')
]

class SearchEvento(forms.Form):
    """Formulário para consulta de eventos da view que lista eventos
    de forma genérica"""
    nome = forms.CharField(required=False, label="Nome do Evento")
    instituicao = forms.ModelChoiceField(queryset=Instituicao.objects.all(), required=False, label="Instituição")
    local = forms.CharField(required=False, label="Local")
    data_inicial = forms.DateField(required=False)

class EventoCreateForm(forms.ModelForm):
    """Formulário para criação de eventos"""
    responsavel = forms.CharField(required=True)
    instituicao = forms.ModelChoiceField(queryset=Instituicao.objects.all(), required=True, label="Instituição")
    data_inicial = forms.CharField(widget=forms.TextInput(attrs={'type': 'date'}), required=False, label="Data Inicial")
    data_final = forms.CharField(widget=forms.TextInput(attrs={'type': 'date'}), required=False, label="Data Final")
    horario_entrada = forms.CharField(required=True)
    horario_saida = forms.CharField(required=True)
    aberto_publico = forms.ChoiceField(choices=ESCOLHA_CHOICES, required=True, label="Aberto ao Público")

    class Meta:
        model = Evento
        fields = ('__all__')

evChurch/apps/evento/views.py
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from ..core.generic_views import SearchCustomView, CustomDetailView
from django.http import HttpResponse
from .forms import *
from .models import Evento

@method_decorator(login_required, name='dispatch')
class EventoView(SearchCustomView):
    """
    View para consulta de Eventos
    """
    form_class = SearchEvento
    model = Evento
    order_field = "nome"
    template_name = "evento/index.html"
    page_title = "Evento"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("evento:evento_index"), "Evento")
    ]

    def get_queryset(self):
        """
        Altera o filtro da evento ::
        """
        queryset = super(EventoView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class EventoDetailView(CustomDetailView):
    """
    View para exibição dos detalhes dos eventos
    """
    model = Evento
    template_name = "evento/detail.html"
    page_title = "Evento"

    def get_context_data(self, **kwargs):
        context = super(EventoDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("evento:evento_index"), "Evento"),
            ("#", self.get_object().id)
        ]

        return context

@login_required
@permission_required("evento.add_evento", raise_exception=True)
def evento_create(request):
    """View para Criar um evento"""
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("evento:evento_index"), "Evento"),
        (reverse("evento:evento_create"), "Novo Evento")
    ]

    form = EventoCreateForm()

    if request.method == 'POST':
        form = EventoCreateForm(request.POST)
        if form.is_valid():
            evento = form.save(commit=False)
            evento.save()

            messages.success(request, "Evento cadastrado com sucesso")
            return redirect(reverse("evento:evento_show", args=[evento.pk]))

    return render(request, "evento/cadastro.html", locals())

@login_required
@permission_required("evento.add_evento", raise_exception=True)
def evento_edit(request, pk):
    """"View para Editar os eventos"""
    evento = get_object_or_404(Evento, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("evento:evento_index"), "Agenda"),
        (reverse("evento:evento_show", args=[pk]), evento.id),
        ("#", "Editar")
    ]

    form = EventoCreateForm(instance=evento)

    if request.method == 'POST':
        form = EventoCreateForm(request.POST, request.FILES, instance=evento)

        if form.is_valid():
            evento = form.save(commit=False)
            evento.save()

            messages.success(request, "Evento alterado com sucesso.")
            return redirect(reverse("evento:evento_show", args=[evento.pk]))

    return render(request, "evento/editar.html", locals())

@login_required
@permission_required("evento.add_evento", raise_exception=True)
def evento_delete(request, pk):
    """
    View responsável por deletar um evento
    """
    evento = get_object_or_404(Evento, pk=pk)

    evento.delete()
    messages.success(request, "Evento deletado com sucesso!")
    return HttpResponse("Evento deletado com sucesso!")

evChurch/apps/evento/templates/evento/cadastro.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/evento.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Cadastrar Evento</h1>
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
        {% include "evento/form.html" %}
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'evento:evento_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/evento/templates/evento/detail.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/evento.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h1 class="title">{{ page_title }}: {{ evento.id }}</h1>
        </div>
        <table class="table table-bordered table-striped">
          <tr>
            <td><strong>Nome:</strong><br> {{ evento.nome|default:"Não informado" }}</td>
            <td><strong>Local:</strong><br> {{ evento.local|default:"Não informado" }}</td>
            <td><strong>Instituição:</strong><br> {{ evento.instituicao|default:"Não informado" }}</td>
            <td><strong>Responsável:</strong><br> {{ evento.responsavel|default:"Não informado" }}</td>
          </tr>
            <tr>
             <td colspan="2"><strong>Data e Horário:</strong><br>
                 De {{ evento.data_inicial|date:"d/m/Y" }} às {{ evento.horario_entrada|default:"Não informado" }} até
                 {{ evento.data_final|date:"d/m/Y" }} às {{ evento.horario_saida|default:"Não informado" }}
             </td>
                <td><strong>Aberto:</strong><br> {{ evento.aberto_publico|default:"Não informado" }}</td>
                <td><strong>Contato:</strong><br> {{ evento.telefone|default:"Não informado" }}</td>
          </tr>
        </table>
      </div>
    </div>
      <div class="form-row">
        <div class="form -btn-actions col">
          <a href="{% url 'evento:evento_index' %}" class="btn btn-default"><< Voltar</a>
        </div>
      </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/evento/templates/evento/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/evento.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Editar Evento</h1>
      <ol class="breadcrumb">
        <li class="active">Preencha os campos corretamente</li>
      </ol>
      <form class="form" method="POST">
        {% csrf_token %}
        {% include "evento/form_edit.html" %}
        <!-- {% bootstrap_form form %} -->
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'evento:evento_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/evento/templates/evento/form.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.local required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.responsavel required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.data_inicial required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.horario_entrada required_css_class="required" %}
  </div>
    <div class="col-3">
    {% bootstrap_field form.data_final required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.horario_saida required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-4">
    {% bootstrap_field form.aberto_publico required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/evento/templates/evento/form_edit.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.local required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.responsavel required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.data_inicial required_css_class="required" %}
  </div>
   <div class="col-3">
    {% bootstrap_field form.horario_entrada required_css_class="required" %}
  </div>
    <div class="col-3">
    {% bootstrap_field form.data_final required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.horario_saida required_css_class="required" %}
  </div>
</div>
<div class="form-row">
    <div class="col-4">
    {% bootstrap_field form.aberto_publico required_css_class="required" %}
  </div>
    <div class="col-4">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/evento/templates/evento/index.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/evento.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>

      </div>
    </div>
  </div>
  <div class="row-list">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered table-striped">
        <thead>
          <th>Ações</th>
          <th>Responsável</th>
          <th>Instituição </th>
          <th>Aberto </th>
          <th>Nome</th>
          <th>Data</th>
        </thead>
        <tbody>
          {% for evento in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'evento:evento_show' evento.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'evento:evento_edit' evento.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:eventoDelete({{evento.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ evento.responsavel|default:"Não informado"}}</td>
              <td>{{ evento.instituicao|default:"Não informado"}}</td>
              <td>{{ evento.aberto_publico|default:"Não informado"}}</td>
              <td>{{ evento.nome|default:"Não informado"}}</td>
              <td>{{ evento.data_inicial|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de um evento -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente esse evento?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirEvento" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function eventoDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirEvento" ).click(function() {
        $.ajax({
          url: pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}