evChurch/apps/usuarios/urls.py
from django.urls import path, include
from . import views

app_name='usuarios'

urlpatterns = [
    path("usuario/", views.UsuarioView.as_view(), name="usuario_index"),
    path("usuario/detalhes/<int:pk>/",
        views.UsuarioDetailView.as_view(), name="usuario_show"),
    path("usuario/cadastrar/",views.usuario_create, name="usuario_create"),
    path("usuario/<int:pk>/editar/",views.usuario_edit, name="usuario_edit"),
    path("usuario/<int:pk>/excluir/", views.usuario_delete, name="usuario_delete")
]

evChurch/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .apps.core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(home), name="root_path"),
    path('core/', include('evChurch.apps.core.urls', namespace='core')),
    path('auth/',
        include('evChurch.apps.authorization.urls', namespace='authorization')),
    path('usuarios/',
        include('evChurch.apps.usuarios.urls', namespace='usuarios')),
    path('instituicoes/',
        include('evChurch.apps.instituicoes.urls', namespace='instituicoes')),
    path('grupos/',
        include('evChurch.apps.grupos.urls', namespace='grupos')),
    path('agenda/',
         include('evChurch.apps.agenda.urls', namespace='agenda')),
    path('ambientes/',
         include('evChurch.apps.ambientes.urls', namespace='ambientes')),
    path('evento/',
         include('evChurch.apps.evento.urls', namespace='evento'))
]

evChurch/apps/usuarios/models.py
from django.db import models
from ..instituicoes.models import Instituicao

class Perfil(models.Model):
    descricao = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.descricao

class Usuario(models.Model):
    nome = models.CharField(max_length=90, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    perfil = models.ForeignKey(Perfil, null=True, blank=True, on_delete=models.CASCADE)
    instituicao = models.ForeignKey(Instituicao, null=True, blank=True, on_delete=models.CASCADE)
    logradouro = models.CharField(max_length=120, null=True, blank=True)
    numero = models.CharField(max_length=10, null=True, blank=True)
    bairro = models.CharField(max_length=100, null=True, blank=True)
    complemento = models.CharField(max_length=80, blank=True, null=True)
    cep = models.CharField(max_length=9, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    telefone = models.CharField(max_length=12, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)

    class Meta:
        permissions = (
            ("pode_cadastrar_usuario", "Pode cadastrar usuário"),
            ("pode_alterar_usuario", "Pode editar usuário"),
            ("pode_excluir_usuario", "Pode excluir usuário"),
        )

    def __str__(self):
        return self.nome

evChurch/apps/usuarios/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Usuario
from localflavor.br.forms import BRStateChoiceField
from ..instituicoes.models import Instituicao

class SearchUsuario(forms.Form):
    """Formulário para consulta de usuários da view que lista usuários
    de forma genérica"""

    nome = forms.CharField(max_length=90, required=False)
    email = forms.EmailField(required=False)

class UsuarioCreateForm(forms.ModelForm):
    """Formulário para criação de ocorrências"""
    email = forms.EmailField(required=True, label="Email")
    instituicao = forms.ModelChoiceField(queryset=Instituicao.objects.all(), required=True, label="Instituição")

    class Meta:
        model = Usuario
        fields = ('__all__')

evChurch/apps/usuarios/views.py
from django.shortcuts import render
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from ..core.generic_views import SearchCustomView, CustomDetailView
from .forms import *
from .models import Usuario
from django.http import HttpResponse

@method_decorator(login_required, name='dispatch')
class UsuarioView(SearchCustomView):
    """
    View para consulta de usuarios
    """
    form_class = SearchUsuario
    model = Usuario
    order_field = "nome"
    template_name = "usuarios/index.html"
    page_title = "Usuários"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("usuarios:usuario_index"), "Usuários")
    ]

    def get_queryset(self):
        """
        Altera o filtro do usuário ::
        """
        queryset = super(UsuarioView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class UsuarioDetailView(CustomDetailView):
    """
    View para exibição dos detalhes do usuário
    """
    model = Usuario
    template_name = "usuarios/detail.html"
    page_title = "Usuário"

    def get_context_data(self, **kwargs):
        context = super(UsuarioDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("usuarios:usuario_index"), "Usuários"),
            ("#", self.get_object().id)
        ]

        return context

@login_required
@permission_required("usuario.add_usuario", raise_exception=True)
def usuario_create(request):
    """View para Criar um usuario"""
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("usuarios:usuario_index"), "Usuários"),
        (reverse("usuarios:usuario_create"), "Novo Usuário")
    ]

    form = UsuarioCreateForm()
    if request.method == 'POST':
        form = UsuarioCreateForm(request.POST)

        if form.is_valid():
            usuario = form.save(commit=False)
            usuario.save()

            messages.success(request, "Usuário cadastrado com sucesso")
            return redirect(reverse("usuarios:usuario_show", args=[usuario.pk]))

    return render(request, "usuarios/cadastro.html", locals())

@login_required
@permission_required("usuario.add_usuario", raise_exception=True)
def usuario_edit(request, pk):
    """"View para Editar os Usuários"""
    usuario = get_object_or_404(Usuario, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("usuarios:usuario_index"), "Usuários"),
        (reverse("usuarios:usuario_show", args=[pk]), usuario.id),
        ("#", "Editar")
    ]

    form = UsuarioCreateForm(instance=usuario)

    if request.method == 'POST':
        form = UsuarioCreateForm(request.POST, request.FILES, instance=usuario)

        if form.is_valid():
            usuario = form.save(commit=False)
            usuario.save()

            messages.success(request, "Usuário alterado com sucesso.")
            return redirect(reverse("usuarios:usuario_show", args=[usuario.pk]))

    return render(request, "usuarios/editar.html", locals())

@login_required
@permission_required("usuario.add_usuario", raise_exception=True)
def usuario_delete(request, pk):
    """
    View responsável por deletar um usuário
    """
    usuario = get_object_or_404(Usuario, pk=pk)

    usuario.delete()
    messages.success(request, "Usuário deletado com sucesso!")
    return HttpResponse("Usuário deletado com sucesso!")

evChurch/apps/usuarios/templates/usuarios/cadastro.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/usuario.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Cadastrar Usuário</h1>
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
        {% include "usuarios/form.html" %}
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'usuarios:usuario_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/usuario.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/usuarios/templates/usuarios/detail.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/usuario.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h1 class="title">{{ page_title }}: {{ usuario.id }}</h1>
        </div>
        <table class="table table-bordered table-striped">
          <tr>
            <td><strong>Nome:</strong><br> {{ usuario.nome|default:"Não informado" }}</td>
            <td><strong>Telefone:</strong><br> {{ usuario.telefone|default:"Não informado" }}</td>
            <td><strong>Email:</strong><br> {{ usuario.email|default:"Não informado" }}</td>
            <td><strong>Perfil:</strong><br> {{ usuario.perfil|default:"Não informado" }}</td>
            <td><strong>Telefone:</strong><br> {{ usuario.telefone|default:"Não informado" }}</td>
          </tr>
          <tr>
             <td><strong>Logradouro:</strong><br> {{ usuario.logradouro|default:"Não informado" }}</td>
             <td><strong>Número:</strong><br> {{ usuario.numero|default:"Não informado" }}</td>
             <td><strong>Bairro:</strong><br> {{ usuario.bairro|default:"Não informado" }}</td>
             <td><strong>Cidade:</strong><br> {{ usuario.cidade|default:"Não informado" }}</td>
             <td><strong>UF:</strong><br> {{ usuario.uf|default:"Não informado" }}</td>
          </tr>
        </table>
      </div>
    </div>
      <div class="form-row">
        <div class="form -btn-actions col">
          <a href="{% url 'usuarios:usuario_index' %}" class="btn btn-default"><< Voltar</a>
        </div>
      </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/usuarios/templates/usuarios/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/usuario.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Editar Usuário</h1>
      <ol class="breadcrumb">
        <li class="active">Preencha os campos corretamente</li>
      </ol>
      <form class="form" method="POST">
        {% csrf_token %}
        {% include "usuarios/form_edit.html" %}
        <!-- {% bootstrap_form form %} -->
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'usuarios:usuario_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

evChurch/apps/usuarios/templates/usuarios/form.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-5">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.email required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.perfil required_css_class="required" %}
  </div>
   <div class="col-4">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
   <div class="col-3">
    {% bootstrap_field form.cep required_css_class="required" %}
  </div>
  <div class="col-5">
    {% bootstrap_field form.logradouro required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.numero required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.complemento required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-5">
    {% bootstrap_field form.cidade required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.bairro required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.uf required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/usuario.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/usuarios/templates/usuarios/form_edit.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-5">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.email required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-4">
    {% bootstrap_field form.perfil required_css_class="required" %}
  </div>
   <div class="col-4">
    {% bootstrap_field form.instituicao required_css_class="required" %}
  </div>
</div>
<div class="form-row">
   <div class="col-3">
    {% bootstrap_field form.cep required_css_class="required" %}
  </div>
  <div class="col-5">
    {% bootstrap_field form.logradouro required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.numero required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.complemento required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-5">
    {% bootstrap_field form.cidade required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.bairro required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.uf required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
{% endblock extra_js %}

evChurch/apps/usuarios/templates/usuarios/index.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/usuario.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>

      </div>
    </div>
  </div>
  <div class="row-list">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered table-striped">
        <thead>
          <th>Ações</th>
          <th>Nome</th>
          <th>Telefone </th>
          <th>Email </th>
          <th>Perfil</th>
        </thead>
        <tbody>
          {% for usuario in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'usuarios:usuario_show' usuario.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'usuarios:usuario_edit' usuario.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:usuarioDelete({{usuario.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ usuario.nome|default:"Não informado"}}</td>
              <td>{{ usuario.telefone|default:"Não informado"}}</td>
              <td>{{ usuario.email|default:"Não informado"}}</td>
              <td>{{ usuario.perfil|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de um usuario -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente esse usuário?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirUsuario" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function usuarioDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirUsuario" ).click(function() {
        $.ajax({
          url: pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}